version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: server-jira-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootBoss123
      MYSQL_DATABASE: jira
      MYSQL_USER: davide
      MYSQL_PASSWORD: davide123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db-jira-container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: davide
      PMA_PASSWORD: davide123

volumes:
  mysql_data:

networks:
  my-network:
